#! /usr/bin/env python3

from flask import Flask, render_template, Markup
from util import getHtml, duplicate, displayArray
from flask_socketio import SocketIO, emit
from multiprocessing import Process
import time
import os
import sys

app = Flask(__name__)
app.config['SECRET_KEY'] = 'secret!'
socketio = SocketIO(app)

myFile=sys.argv[-1]
fileLocation=myFile

@app.route('/')
def home():
    jsloc, css, body = displayArray(myFile)
    return render_template('main.html', jsloc=jsloc, css=css, body=Markup(body))
@socketio.on('connect')
def connect():
    print('Connected to client')
@socketio.on('disconnect')
def disconnect():
    print('Client disconnected')
@socketio.on('checkOnUpdate') 
def checkOnUpdate():
    lastModified=os.path.getmtime(fileLocation)
    timeSinceModified=int(time.time()-lastModified)
    print(timeSinceModified)
    if timeSinceModified<=2:
        emit('reload')
        time.sleep(5)
        print('Send Help')

if __name__ == '__main__':
    def startFlask():
        socketio.run(app, port=5000, debug=True)
    try:
        flask=Process(target=startFlask)
        flask.start()
    except KeyboardInterrupt:
        try:
            os.remove(a)
        except OSError as e: # name the Exception `e`
            print("Failed with:", e.strerror) # look what it says
            print("Error code:", e.code)
        print("Terminating flask server.")
        flask.terminate()
        flask.join()
